config/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path("admin/", admin.site.urls),
    path('', include('main.urls', namespace='main')),
]

main/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page

from main.apps import MainConfig
from main.views import MessageListView, MessageDeleteView, MessageDetailView, MessageCreateView, MessageUpdateView, \
    ContactsTemplateView

# Присваиваем переменной название приложения автоматически из системных файлов фреймворка Django
app_name = MainConfig.name

# Прописываем к функциям  и их наменования
# Пример path('create/', MessageCreateView.as_view(), name='create'),
# первой переменной в скобках указываем по какому пути страница будет отображаться на сайте (http://127.0.0.1:8000/create/)
# второй переменной указываем на метод класса, который мы написали в view.py, в данном случае это класс создания объектов модели Product
# третьей переменной указываем наименование url путя, можно задать любое, чтобы потом к нему обращаться

urlpatterns = [
    path('', MessageListView.as_view(), name='list'),
    path('create/', MessageCreateView.as_view(), name='create'),
    path('delete/<int:pk>/', MessageDeleteView.as_view(), name='delete'),
    path('product/<int:pk>/', cache_page(60)(MessageDetailView.as_view()), name='view'),
    path('edit/<int:pk>/', MessageUpdateView.as_view(), name='edit'),
    path('contacts/', ContactsTemplateView.as_view(), name='contacts'),
]

main/models.py
from django.db import models


class Message(models.Model):
    date_m = models.CharField(max_length=30, blank=True, null=True)
    info_m = models.CharField(max_length=30, blank=True, null=True)
    application_m = models.CharField(max_length=30, blank=True, null=True)
    action_m = models.CharField(max_length=150, blank=True, null=True)

    class Meta:
        managed = False
        db_table = 'message'

main/forms.py
from django.forms import ModelForm

from main.models import Message
"""
Здесь представлены формы моделей в которых :
- ProductForm представляет форму создания и редактирования продукта
- CategoryForm представляет форму создания и редактирования категории
в model = ... мы пишем название модели к которой пишем форму
fields = "__all__" указывает что все поля модели будут использоваться в форме, если они не указаны явно.
"""


class MessageForm(ModelForm):
    class Meta:
        model = Message
        fields = '__all__'

main/views.py
from django.shortcuts import render
from django.urls import reverse_lazy, reverse
from django.views.generic import CreateView, ListView, DeleteView, DetailView, UpdateView, TemplateView
from django.db.models import Q

from main.forms import MessageForm
from main.models import Message


class MessageCreateView(CreateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('main:list')


class MessageUpdateView(UpdateView):
    model = Message
    form_class = MessageForm
    success_url = reverse_lazy('main:list')

    def get_success_url(self):
        return reverse('main:view', args=[self.kwargs.get('pk')])


class MessageListView(ListView):
    model = Message
    template_name = 'main/message_list.html'

    def get_queryset(self): # новый
        query = self.request.GET.get('q')
        if query:
            object_list = Message.objects.filter(
                Q(title__icontains=query))
            return object_list
        else:
            return Message.objects.all()


class MessageDetailView(DetailView):
    model = Message


class MessageDeleteView(DeleteView):
    model = Message
    success_url = reverse_lazy('main:list')


class ContactsTemplateView(TemplateView):
    template_name = 'main/contacts.html'

    def post(self, request, *args, **kwargs):
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')

        print(f"\n\nИмя - {name}\n"
              f"Телефон - {phone}\n"
              f"Сообщение - {message}\n\n")

        return super().get(request, *args, **kwargs)


def contacts(request):
    if request.method == 'POST':
        name = request.POST.get('name')
        phone = request.POST.get('phone')
        message = request.POST.get('message')

        print(f"\n\nИмя - {name}\n"
              f"Телефон - {phone}\n"
              f"Сообщение - {message}\n\n")

    return render(request, 'contacts.html')

main/templates/main/contacts.html
{% extends 'main/home.html' %}
{% block content %}
<div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
    <h1 class="display-4">Контакты</h1>
</div>

<div class="container">
    <div class="row text-start">
        <div class="col-lg-9 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-body">
                    <table class="table table-striped">
                        <tr>
                            <td class="w-25">Страна</td>
                            <td>Россия</td>
                        </tr>
                        <tr>
                            <td class="w-25">ИНН</td>
                            <td>91-1144442</td>
                        </tr>
                        <tr>
                            <td class="w-25">Адрес</td>
                            <td>ParserLogs,WA,98052-6399</td>
                        </tr>
                    </table>
                </div>
            </div>
        </div>
        <div class="col-lg-3 col-md-6 col-sm-12">
            <div class="card mb-4 box-shadow">
                <div class="card-header">
                    <h4 class="my-0 font-weight-normal">Свяжитесь с нами</h4>
                </div>
                <div class="card-body">
                    <form method="post" action="" class="form-floating">
                        {% csrf_token %}
                        <div class="mb-3">
                            <label for="name">Имя</label>
                            <input type="text" name="name" class="form-control" id="name" placeholder="Ваше имя"
                                   required>
                        </div>
                        <div class="mb-3">
                            <label for="phone">Телефон</label>
                            <input type="text" name="phone" class="form-control" id="phone"
                                   placeholder="Контактный телефон" required>
                        </div>
                        <div class="mb-3">
                            <label for="message">Сообщение</label>
                            <textarea type="text" name="message" class="form-control" id="message"
                                      placeholder="Напишите сообщение" required></textarea>
                        </div>
                        <button type="submit" class="btn btn-lg btn-block btn-outline-primary">Отправить</button>
                    </form>
                </div>
            </div>
        </div>
    </div>
    {% endblock %}

main/templates/main/home.html
{% load static %}
<!doctype html>
<html lang="en" data-bs-theme="auto">
<head>
    <script src="{% static 'js/color-modes.js' %}"></script>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.122.0">
    <title>Album example · Bootstrap v5.3</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.3/examples/album/">


    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@docsearch/css@3">

    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Favicons -->
    <link rel="apple-touch-icon" href="/docs/5.3/assets/img/favicons/apple-touch-icon.png" sizes="180x180">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-32x32.png" sizes="32x32" type="image/png">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon-16x16.png" sizes="16x16" type="image/png">
    <link rel="mask-icon" href="/docs/5.3/assets/img/favicons/safari-pinned-tab.svg" color="#712cf9">
    <link rel="icon" href="/docs/5.3/assets/img/favicons/favicon.ico">
    <meta name="theme-color" content="#712cf9">


    <style>
        .bd-placeholder-img {
          font-size: 1.125rem;
          text-anchor: middle;
          -webkit-user-select: none;
          -moz-user-select: none;
          user-select: none;
        }

        @media (min-width: 768px) {
          .bd-placeholder-img-lg {
            font-size: 3.5rem;
          }
        }

        .b-example-divider {
          width: 100%;
          height: 3rem;
          background-color: rgba(0, 0, 0, .1);
          border: solid rgba(0, 0, 0, .15);
          border-width: 1px 0;
          box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
        }

        .b-example-vr {
          flex-shrink: 0;
          width: 1.5rem;
          height: 100vh;
        }

        .bi {
          vertical-align: -.125em;
          fill: currentColor;
        }

        .nav-scroller {
          position: relative;
          z-index: 2;
          height: 2.75rem;
          overflow-y: hidden;
        }

        .nav-scroller .nav {
          display: flex;
          flex-wrap: nowrap;
          padding-bottom: 1rem;
          margin-top: -1px;
          overflow-x: auto;
          text-align: center;
          white-space: nowrap;
          -webkit-overflow-scrolling: touch;
        }

        .btn-bd-primary {
          --bd-violet-bg: #712cf9;
          --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

          --bs-btn-font-weight: 600;
          --bs-btn-color: var(--bs-white);
          --bs-btn-bg: var(--bd-violet-bg);
          --bs-btn-border-color: var(--bd-violet-bg);
          --bs-btn-hover-color: var(--bs-white);
          --bs-btn-hover-bg: #6528e0;
          --bs-btn-hover-border-color: #6528e0;
          --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
          --bs-btn-active-color: var(--bs-btn-hover-color);
          --bs-btn-active-bg: #5a23c8;
          --bs-btn-active-border-color: #5a23c8;
        }

        .bd-mode-toggle {
          z-index: 1500;
        }

        .bd-mode-toggle .dropdown-menu .active .bi {
          display: block !important;
        }
    </style>


</head>
<body>
<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
    <symbol id="check2" viewBox="0 0 16 16">
        <path d="M13.854 3.646a.5.5 0 0 1 0 .708l-7 7a.5.5 0 0 1-.708 0l-3.5-3.5a.5.5 0 1 1 .708-.708L6.5 10.293l6.646-6.647a.5.5 0 0 1 .708 0z"/>
    </symbol>
    <symbol id="circle-half" viewBox="0 0 16 16">
        <path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z"/>
    </symbol>
    <symbol id="moon-stars-fill" viewBox="0 0 16 16">
        <path d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z"/>
        <path d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z"/>
    </symbol>
    <symbol id="sun-fill" viewBox="0 0 16 16">
        <path d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z"/>
    </symbol>
</svg>

<div class="dropdown position-fixed bottom-0 end-0 mb-3 me-3 bd-mode-toggle">
    <button class="btn btn-bd-primary py-2 dropdown-toggle d-flex align-items-center"
            id="bd-theme"
            type="button"
            aria-expanded="false"
            data-bs-toggle="dropdown"
            aria-label="Toggle theme (auto)">
        <svg class="bi my-1 theme-icon-active" width="1em" height="1em">
            <use href="#circle-half"></use>
        </svg>
        <span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
    </button>
    <ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="light"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#sun-fill"></use>
                </svg>
                Light
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center" data-bs-theme-value="dark"
                    aria-pressed="false">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#moon-stars-fill"></use>
                </svg>
                Dark
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
        <li>
            <button type="button" class="dropdown-item d-flex align-items-center active" data-bs-theme-value="auto"
                    aria-pressed="true">
                <svg class="bi me-2 opacity-50" width="1em" height="1em">
                    <use href="#circle-half"></use>
                </svg>
                Auto
                <svg class="bi ms-auto d-none" width="1em" height="1em">
                    <use href="#check2"></use>
                </svg>
            </button>
        </li>
    </ul>
</div>


<header data-bs-theme="dark">
    {% include 'main/includes/inc_menu.html' %}
</header>

<main>

    <section class="py-5 text-center container">
        <div class="row py-lg-5">
            <div class="col-lg-6 col-md-8 mx-auto">
                <h1 class="fw-light"> Ваш индивидуальный парсер вирусов </h1>
                <p class="lead text-body-secondary">Осторожно, вирусы:</p>

            </div>
        </div>
    </section>



    {% block content %}
    {% endblock %}

</main>

<footer class="text-body-secondary py-5">
    <div class="container">
        <p class="float-end mb-1">
            <a href="#">Back to top</a>
        </p>
        <p class="mb-1">&copy; ParserLogs</p>
        <p class="mb-0">Обезопасьте себя! <a href="{% url 'main:list' %}">Посмотрите все подозрения на вирусы!</a></p>
    </div>
</footer>
<script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>

</body>
</html>

main/templates/main/includes/inc_menu.html
<div class="collapse text-bg-dark" id="navbarHeader">
    <div class="container">
        <div class="row">
            <div class="col-sm-8 col-md-7 py-4">
                <h4>𓆩Индивидуальный парсер𓆪</h4>
                <p class="text-body-secondary">Просканирую журнал событий 360 total security и покажу все вирусы</p>
            </div>
            <div class="col-sm-4 offset-md-1 py-4">
                <h4>Навигация</h4>
                <ul class="list-unstyled">

                    <li><a href="{% url 'main:list' %}" class="text-white">Главная</a></li>
                    <li><a href="{% url 'main:contacts' %}" class="text-white">Контакты</a></li>

                </ul>
            </div>
        </div>
    </div>
</div>
<div class="navbar navbar-dark bg-dark shadow-sm">
    <div class="container">
        <a href="#" class="navbar-brand d-flex align-items-center">
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarHeader"
                aria-controls="navbarHeader" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
    </div>
</div>

main/templates/main/message_confirm_delete.html
{% extends 'main/home.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3"
        <div class="col">
            <div class="card shadow-sm">
                <form method="post">
                    {% csrf_token %}
                    <p>Хотите удалить сообщение о"{{ object.application_m }}"?</p>
                    <button type="submit" class="btn btn-success">Подвердить</button>
                    <a class="btn btn-primary" href="{% url 'main:list'%}"
                                       role="button">Отменить</a>
                </form>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/message_detail.html
{% extends 'main/home.html' %}
{% block content %}
<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row row-cols-1 row-cols-sm-2 row-cols-md-2 g-3"
            <div class="col">
                <div class="card shadow-sm">
                    <div class="card-body">
                        <p class="card-text">{{ object.info_m }}</p>
                        <p class="card-text">Приложение: {{ object.application_m }}</p>
                        <p class="card-text">Описание: {{ object.action_m }}</p>
                        <p class="card-text">Дата создания: {{ object.date_m }}</p>
                        <div class="d-flex justify-content-between align-items-center">
                            <div class="btn-group">
                                <a class="btn btn-primary" href="{% url 'main:list' %}" role="button">Вернуться</a>
                            </div>
<!--                            <small class="text-body-secondary">Просмотры: {{ object.views }}</small>-->
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
{% endblock %}

main/templates/main/message_form.html
{% extends 'main/home.html' %}
{% block content %}
<div class="container">
    <form method="post">
        <div class="row">
            <div class="col-6">
                <div class="card">
                    {% if object %}
                    <p class="card-text">Редактирование сообщения</p>
                    {% else %}
                    <p class="card-text">Создание сообщения</p>
                    {% endif%}
                    <div class="card-body">
                        {% csrf_token %}
                        {{ form.as_p}}
                    </div>
                    <button type="submit" class="btn btn-success">
                        {% if object %}
                        Сохранить
                        {% else %}
                        Создать
                        {% endif%}
                    </button>
                </div>
            </div>
        </div>
    </form>
</div>
{% endblock %}

main/templates/main/message_list.html
{% extends 'main/home.html' %}
{% block content %}
<div class="row text-center">
<form action="{% url 'main:list' %}" method="get">
<input type="text" name="q" placeholder="Поиск по названию">
    <button type="submit" class="btn btn-primary">Найти</button>
</form>
</div>

<div class="album py-5 bg-body-tertiary">
    <div class="container">
        <div class="row ">
            <div class="row text-center">
                {% for object in object_list %}
                <div class="col-4">
                    <div class="card shadow-sm">
                        <div class="card-body">
                            <p class="card-text">{{ object.info_m }}</p>
                            <p class="card-text">{{ object.application_m }}</p>
                            <div class="d-flex justify-content-between align-items-center">
                                <div class="btn-group-center">
                                    <a class="btn btn-primary" href="{% url 'main:view' object.pk %}"
                                       role="button">Посмотреть</a>
                                    <a class="btn btn-primary" href="{% url 'main:edit' object.pk %}"
                                       role="button">Редактировать</a>
                                    <a class="btn btn-warning" href="{% url 'main:delete' object.pk %}"
                                       role="button">Удалить</a>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
                {% endfor %}
            </div>
        </div>
    </div>
</div>
{% endblock %}